import { richTextResolver } from '@storyblok/astro'

// Add numbers to ordered list items
const ordered_list = ({ children }) => {
	let counter = 0
	const numberedItems = children.map((numberedItem) => {
		counter += 1
		return `${counter}. ${numberedItem}`
	})
	return `${numberedItems.join('')}`
}

// Display a generic fallback when the rich text field is empty
const paragraph = ({ children }) => {
	return children === undefined ? 'Provide content' : `\n${children.join('')}\n`
}

// Create custom resolvers for common types supported in the richtext package.
const mdResolver = richTextResolver({
	resolvers: {
		blockquote: ({ children }) => `> ${children[0].replace('\n', '')}`,
		bold: ({ text }) => `**${text}**`,
		bullet_list: ({ children }) => `- ${children.join('- ')}`,
		code: ({ text }) => `\`${text}\``,
		code_block: ({ children }) => `\n\`\`\`\n${children}\n\`\`\`\n`,
		heading: ({ attrs, children }) =>
			`\n${'#'.repeat(attrs.level)} ${children}\n`,
		image: ({ attrs }) =>
			`![${attrs.alt || 'Image description'}](${attrs.src})`,
		italic: ({ text }) => `*${text}*`,
		link: ({ attrs, text }) => `[${text}](${attrs?.href})`,
		list_item: ({ children }) => `${children[0].replace('\n', '')}`,
		ordered_list: ordered_list,
		paragraph: paragraph,
	},
})

// Decode the sanitized HTML generated by the rich text package
export const convertedMarkdown = (richTextField) => {
	// Handle null/undefined input
	if (!richTextField) {
		return 'No content available'
	}

	try {
		const decodeHTML = mdResolver.render(richTextField)
		return String(decodeHTML)
			.replaceAll('&amp;', '&')
			.replaceAll('&lt;', '<')
			.replaceAll('&gt;', '>')
			.replaceAll('&quot;', '"')
			.replaceAll('&#039;', "'")
	} catch (error) {
		console.error('Error converting richtext to markdown:', error)
		return 'Content conversion failed'
	}
}
